# Generated by Django 2.2a1 on 2019-03-15 17:25

import accounts.managers
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(help_text='First Name', max_length=128, null=True, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Last Name', max_length=128, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, help_text='Primary Phone Number', max_length=17, null=True, verbose_name='phone')),
                ('cell', models.CharField(blank=True, help_text='Cellphone Number', max_length=17, null=True, verbose_name='cell')),
                ('title', models.CharField(blank=True, help_text='Professional Title', max_length=128, null=True, verbose_name='title')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('role', models.CharField(default='PROJECT_MANAGER', max_length=255)),
                ('color', colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['company', 'first_name', 'last_name', 'title', 'email', 'cell'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
